### ISSUE TITLE
exist 5.2. installation fails

### ISSUE THREAD

**Issue by schnoepf** [telota/existance#10]
When using existance with 5.2., existance faces different problems:
1. The installer cannot be found
2. If the installer is manually added to `/var/cache/existance` (`exist-installer-5.2.0.jar`), existance brings up some html-code and breaks up in the end.

**Comment by schnoepf** [comment]
does existance use `java -jar eXist-{version}.jar -console`?

**Comment by funkyfuture** [comment]
that [seems to be the case](https://github.com/telota/existance/search?q=java+-jar&unscoped_q=java+-jar).

**Comment by schnoepf** [comment]
solved, as now existance5.sh does the job...more or less
