### ISSUE TITLE
Retain monex/instances.xml with an upgrade

### ISSUE THREAD

**Issue by funkyfuture** [telota/existance#3]
@schnoepf mentions in #1 that a configuration file `monex/instances.xml` shall also be preserved during an update.
looking at two of the instances i find that one has such file in its `data` folder (and is thus preserved anyway) and the other has none at all.
so, what is the path from eXist's installation root to that file?

**Comment by schnoepf** [comment]
eXist mentions: (/apps/monex/remotes.html)
/db/apps/monex/instances.xml
but in the filesystem the file seems to be unreachable.

**Comment by funkyfuture** [comment]
probably: `./data/expathrepo/monex-0.9.16/instances.xml`, but as mentioned before, that is retained (obviously, it exists in the filesystem). may your problems be caused by the monex upgrade?

**Comment by schnoepf** [comment]
No, I assume that this file is only edible within the database, not via file system.

**Comment by funkyfuture** [comment]
it's not an issue of this software then.
