### ISSUE TITLE
Stating the obvious: Java is required

### ISSUE THREAD

**Issue by suchmaske** [telota/existance#8]
On a fresh server installing existdb fails if Java is not installed. Java should be mentioned as a requirement on the readme.

**Comment by funkyfuture** [comment]
yeah, well generically put: all of exist-db's requirements.

**Comment by suchmaske** [comment]
Well, yeah. I guess from a usability standpoint it should check whether Java is installed before trying to run the installation to not tamper with the file system unnecessarily. (Although rollbacks happen.)

**Comment by funkyfuture** [comment]
like the other documentation issues you raised (and there are more), it boils down to the questions to whom the docs are targeted at and what knowledge can be assumed by the consumer. obviously you had all the knowledge to solve the issues.

> it should check whether Java is installed

at some point it would also have to check whether the required Java version is installed. it would have to check whether `nginx` and `systemd` are installed as well. i don't think it's worth to add code that needs to be maintained in these regards.

the tool emerged from the need to automate repeatative tasks and ensure that all necessary tweaks are made. not to free one from autonomous thinking.

maybe the Ansible role that is used to setup the hosts (and this tool) may be generalized and added as *reference* here.
